name: quiz_ia
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  dartz: ^0.10.1
  envied: ^0.5.3
  flutter_gemini: ^2.0.3
  flutter_svg: ^2.0.9
  flutter_riverpod: ^2.4.9
  freezed_annotation: ^2.4.1
  go_router: ^13.0.1
  intl: ^0.18.1
  flutter_secure_storage: ^9.0.0
  riverpod_annotation: ^2.3.3
  retrofit: '>=4.0.0 <5.0.0'
  json_annotation: ^4.8.1
  dio: ^5.4.1
  slugify: ^2.0.0

  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.8
  envied_generator: ^0.5.3
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  lint: ^1.8.2
  mockito: ^5.4.4
  mocktail: ^1.0.2
  riverpod_generator: ^2.3.9
  retrofit_generator: '>=7.0.0 <8.0.0'

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true

  main_locale: fr
